---
version: "3"
services:

  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /srv/nas/config/deluge:/config
      - /srv/nas/storage/Torrents:/downloads
      - /srv/nas/storage/Media:/media
    ports:
      - 8112:8112
      - 6882:6881
      - 6882:6881/udp
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
    volumes:
      - /srv/nas/config/jackett:/config
      - /srv/nas/storage/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    network_mode: "host"
    volumes:
      - /srv/nas/config/jellyfin:/config
      - /srv/nas/storage/Media:/media
    restart: "unless-stopped"
  
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/nas/config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/nas/config/radarr:/config
      - /srv/nas/storage/Media/Movies:/movies #optional
      - /srv/nas/storage/Torrents/:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /srv/nas/config/sonarr:/config
      - /srv/nas/storage/Media/TV:/tv #optional
      - /srv/nas/storage/Torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped